version: '3'
services:
  barbuddyapi:
    build: backend/
    image: localhost:5000/barbuddyapi
    container_name: barbuddyapi
    tty: true
    stdin_open: true
    depends_on:
      - barbuddydb

  barbuddydb:
    build: database/
    image: localhost:5000/barbuddydb
    container_name: barbuddydb


  barbuddyfe:
    build: frontend/
    image: localhost:5000/barbuddyfe
    container_name: barbuddyfe
    depends_on:
      - barbuddyapi
