create table catalog(
  catalog_id integer primary key generated by default as identity,
  catalog varchar not null primary key check(catalog != '')
);

create table recipe_category(
  category_id integer primary key generated by default as identity,
  category varchar not null primary key check(category != '')
);

create table recipe(
  recipe_id integer primary key generated by default as identity,
  name varchar unique check(recipe_name != ''),
  description varchar,
  catalog varchar references catalog(catalog) on delete set null on update cascade,
  category varchar references recipe_category on delete set null on update cascade,
  directions text,
  story text,
  active boolean default false not null,
  created timestamp with time zone default CURRENT_TIMESTAMP not null
);

create table ingredient(
  ingredient_id integer primary key generated by default as identity,
  ingredient varchar unique check(ingredient != ''),
  parent_ingredient_id integer references ingredient(ingredient_id) on delete set null on update cascade,
  description varchar
);

create table ingredient_sub(
  ingredient_id integer references ingredient(ingredient_id) on update cascade not null,
  sub_ingredient_id integer references ingredient(ingredient_id) on update cascade not null,
  ratio numeric not null default 1,
  constraint ingredient_sub_pk primary key(ingredient_id, sub_ingredient_id)
);

create table unit(
  unit_id integer primary key generated by default as identity,
  unit varchar unique check(unit != ''),
  plural varchar not null,
  abbreviation varchar not null,
  decilitre_ratio numeric
);

create table recipe_ingredient(
  recipe_id integer references recipe(recipe_id) on update cascade not null,
  ingredient_id integer references ingredient(ingredient_id) on update cascade not null,
  amount numeric not null,
  unit_id integer references unit(unit_id) on delete set null on update cascade,
  constraint recipe_ingredients_pk primary key(recipe_id, ingredient_id)
);

create table appuser(
  user_id integer primary key generated by default as identity,
  email varchar not null check(email != ''),
  password varchar not null check(password != '')
);

create table pantry(
  user_id integer references appuser(user_id) on update cascade not null,
  ingredient_id integer references ingredient(ingredient_id) on update cascade not null,
  amount numeric,
  unit varchar references unit(unit) on delete set null on update cascade,
  constraint pantry_pk primary key(user_id, ingredient_id)
);

create table fav_recipe(
  user_id integer references appuser(user_id) on update cascade not null,
  recipe_id integer references recipe(recipe_id) on update cascade not null,
  constraint fav_recipe_pk primary key(user_id, recipe_id)
);

create table fav_ingredient(
  user_id integer references appuser(user_id) on update cascade not null,
  ingredient_id varchar references ingredient(ingredient_id) on update cascade not null,
  constraint fav_ingredient_pk primary key(user_id, ingredient_id
);

