create table catalog(
  catalog varchar not null primary key check(catalog != '')
);

create table recipe_category(
  category varchar not null primary key check(category != '')
);

create table recipe(
  recipe_name varchar primary key check(recipe_name != ''),
  description varchar,
  catalog varchar references catalog(catalog) on delete set null on update cascade,
  category varchar references recipe_category on delete set null on update cascade,
  directions text,
  story text,
  active boolean default false not null
);

create table ingredient(
  ingredient varchar primary key check(ingredient != ''),
  category varchar references ingredient(ingredient) on delete set null on update cascade,
  description varchar
);

create table ingredient_sub(
  ingredient varchar references ingredient(ingredient) on update cascade not null,
  ingredient_sub varchar references ingredient(ingredient) on update cascade not null,
  ratio numeric not null default 1,
  constraint ingredient_sub_pk primary key(ingredient, ingredient_sub)
);

create table unit(
  unit varchar primary key check(unit != ''),
  plural varchar not null,
  abbreviation varchar not null,
  decilitre_ratio numeric
);

create table recipe_ingredients(
  recipe_name varchar references recipe(recipe_name) on update cascade not null,
  ingredient varchar references ingredient(ingredient) on update cascade not null,
  amount numeric not null,
  unit varchar references unit(unit) on delete set null on update cascade,
  constraint recipe_ingredients_pk primary key(recipe_name, ingredient)
);

create table appuser(
  user_id integer primary key generated by default as identity,
  email varchar not null check(email != ''),
  password varchar not null check(password != '')
);

create table pantry(
  user_id integer references appuser(user_id) on update cascade not null,
  ingredient varchar references ingredient(ingredient) on update cascade not null,
  amount numeric,
  unit varchar references unit(unit) on delete set null on update cascade,
  constraint pantry_pk primary key(user_id, ingredient)
);

create table fav_recipe(
  user_id integer references appuser(user_id) on update cascade not null,
  recipe_name varchar references recipe(recipe_name) on update cascade not null,
  constraint fav_recipe_pk primary key(user_id, recipe_name)
);

create table fav_ingredient(
  user_id integer references appuser(user_id) on update cascade not null,
  ingredient varchar references ingredient(ingredient) on update cascade not null,
  constraint fav_ingredient_pk primary key(user_id, ingredient)
);

