#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER barbuddy WITH ENCRYPTED PASSWORD '$BARBUDDY_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE postgres TO barbuddy;
EOSQL

